# Generated by Django 4.2.7 on 2023-11-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(default='', max_length=15),
        ),
    ]
